# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CLUSTER_NAME: "cluster-1"
  PROJECT_ID_GCP: "coral-hydra-327215"
  REGION: "us-central1-c"
  INSTALL_VOTTING_APP: 'true'
  INSTALL_GRAFANA: 'true'
  INSTALL_PROMETHEUS: 'true'
  INSTALL_KUBE_METRICS: 'true'
  INSTALL_NODE_EXPORTER_METRICS: 'true'
  INSTALL_DEPENDENCIES: 'true'
  RBAC_INSTALL_DEPENDENCIES: 'true'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: gcloud
        uses: google-github-actions/setup-gcloud@master

        with:
          version: '299.0.0'

          project_id: ${{ env.PROJECT_ID_GCP }}
          service_account_key: ${{ secrets.GCP_SECRET }}

      - name: gcloud environment
        run: |-
          GCP_CLUSTER=${{ env.CLUSTER_NAME }}
          GCP_REGION=${{ env.REGION }}

          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials "${GCP_CLUSTER}" --region "${GCP_REGION}"

      - name: Install dependencies (if needed)
        if: ${{ env.INSTALL_DEPENDENCIES == 'true' }}
        run: |-
          .github/scripts/dependencies.sh

      - name: Check namespaces needed
        run: |-
          .github/scripts/check_namespaces.sh

      - name: Install rights for creating rbac's (GKE dependency)
        if: ${{ env.RBAC_INSTALL_DEPENDENCIES == 'true' }}
        run: |-
          ACCOUNT=$(gcloud info --format='value(config.account)')
          kubectl create clusterrolebinding owner-cluster-admin-binding \
              --clusterrole cluster-admin \
              --user $ACCOUNT

      - name: Install Kube Metrics
        if: ${{ env.INSTALL_KUBE_METRICS == 'true' }}
        run: |-
          kubectl apply -f kube_metrics_install/.

      - name: Install Node Exporter Metrics
        if: ${{ env.INSTALL_NODE_EXPORTER_METRICS == 'true' }}
        run: |-
          kubectl apply -f node_exporter_metrics_install/.

      - name: Install Prometheus
        if: ${{ env.INSTALL_PROMETHEUS == 'true' }}
        run: |-
          kubectl apply -f prometheus_install/.

      - name: Install Grafana
        if: ${{ env.INSTALL_GRAFANA == 'true' }}
        run: |-
          kubectl apply -f grafana_install/.

      - name: Install Demo Voting App
        if: ${{ env.INSTALL_VOTTING_APP == 'true' }}
        run: |-
          kubectl apply -f demo_voting_app/. -n vote

      - name: Test kubectl
        run: |
          sudo su
          kubectl cluster-info
          kubectl get pods -A
